import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="h-22 text-white bg-amber-300">
          <h1 className="flex justify-center font-bold text-2xl">Header</h1>
        </header>

        {children}
        <footer className="h-22 text-white bg-amber-300">
          <h1 className="flex justify-center font-bold text-2xl">Footer</h1>
        </footer>
      </body>
    </html>
  );
}
